---

language: python
python: "2.7"
services:
  - docker

before_install:
  - sudo apt-get autoremove -y -qq
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y python-apt python-pycurl locales
  - echo 'en_US.UTF-8 UTF-8' | sudo tee /var/lib/locales/supported.d/local

install:
  - pip install ansible=="2.4.2.0"

script:
  - echo localhost > inventory

  - docker build -f tests/Dockerfile-ubuntu16.04 -t monit_xenial .
